KO: "miR-455_null"
WT: "wild-type"

samples:
  KO_1:
    reads:
     - "/Users/logan/Documents/Snakemake_RNAseq/data/SRR30184267_1.fastq.gz"
     - "/Users/logan/Documents/Snakemake_RNAseq/data/SRR30184267_2.fastq.gz"
    condition: "KO"
  KO_2:
    reads:
     - "/Users/logan/Documents/Snakemake_RNAseq/data/SRR30184268_1.fastq.gz"
     - "/Users/logan/Documents/Snakemake_RNAseq/data/SRR30184268_2.fastq.gz"
    condition: "KO"
  KO_3:
    reads:
     - "/Users/logan/Documents/Snakemake_RNAseq/data/SRR30184269_1.fastq.gz"
     - "/Users/logan/Documents/Snakemake_RNAseq/data/SRR30184269_2.fastq.gz"
    condition: "KO"
  WT_1:
    reads:
     - "/Users/logan/Documents/Snakemake_RNAseq/data/SRR30184270_1.fastq.gz"
     - "/Users/logan/Documents/Snakemake_RNAseq/data/SRR30184270_2.fastq.gz"
    condition: "WT"
  WT_2:
    reads:
     - "/Users/logan/Documents/Snakemake_RNAseq/data/SRR30184271_1.fastq.gz"
     - "/Users/logan/Documents/Snakemake_RNAseq/data/SRR30184271_2.fastq.gz"
    condition: "WT"
  WT_3:
    reads:
     - "/Users/logan/Documents/Snakemake_RNAseq/data/SRR30184272_1.fastq.gz"
     - "/Users/logan/Documents/Snakemake_RNAseq/data/SRR30184272_2.fastq.gz"
    condition: "WT"

wd: "/Users/logan/Documents/Snakemake_RNAseq/"

reference: "/Users/logan/Documents/Snakemake_RNAseq/data/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa"

annotation_file: '/Users/logan/Documents/Snakemake_RNAseq/data/Mus_musculus/UCSC/mm10/Annotation/Genes/genes.gtf'
annotation_file_type: 'GTF'

# metadata: "/Users/logan/Documents/SampleSheetGenerator/metadata.csv"

# fastp
## read lengths
minimum_length: 50
maximum_length: 0
## Start/End Quality trimming
mean_quality: 20
window_size: 4
## Base Quality Filtering
disable_filtering: False
minimum_quality: 15
max_unqualified: 40
average_minumim: 0
## complexity filtering
complexity_filter: True
complexity_minimum: 30
## Adapter trimming (auto detecting adapters will disable the given adapters)
auto_detect_adapters: True
adapter_read_1: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
adapter_read_2: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
